### ISSUE TITLE
Field doesn't reflect server side validity after blur

### ISSUE THREAD

**Issue by tmattsso** [vaadin/vaadin-text-field-flow#15]
The blur event calls validate(), which checks isRequired.

this leads to e.g. server-side validators not being run on blur, leading to wrong state (invalid but looks valid)

**Comment by johannesh2** [comment]
Hi. Is anything happening to this? Bakery order editor behaves strangely apparently because of this issue.

**Comment by Legioth** [comment]
This is fundamentally a conflict between validation happening on the server and validation happening on the client. One thought on how to approach this problem might be enhance the `HasValidation` to allow configuring whether the actual validation status should be ultimately based on server-side or client-side data.

One approach for this might be to replace the `boolean` parameter to `setInvalid` with an enum with three values:
* `INVALID` overrides the regular client-side validation logic with a simple callback that always returns `false`.
* `VALID` overrides the regular client-side validation logic with a simple callback that always returns `true`.
* `CLIENT_DECIDIES` is the default setting that preserves the original client-side validation logic.

**Comment by pleku** [comment]
Need to revisit this after https://github.com/vaadin/flow/issues/3229 is done.

**Comment by denis-anisimov** [comment]
As I understand this is not valid anymore.
Text field by default send the value update on blur nowadays instead of on every key press.
At least I see validation being run on blur.

If not then the exact usecase is required so it's possible to check whether it works or not: the description contains some method and event references whose source I don't really understand (the client side/the server side). Also `Binder` should have been involved somehow since the validators (server-side) are mentioned but it's not clear in which way.
Please reopen with exact steps to reproduce if it's still valid.
