### ISSUE TITLE
IntegerNumberField

### ISSUE THREAD

**Issue by dve** [vaadin/vaadin-text-field-flow#151]
The `NumberField` is using `Double` as the value type, which makes it necessary to convert the value to an `Integer`. It would be much easier if there is an `IntegerNumberField`, and maybe a `FloatNumberField` and a `DoubleNumberField`

**Comment by denis-anisimov** [comment]
The original `NumberField` transfers a double from the client to the server side.
That means that it's possible to set a double on the client side.
Then it's not clear what to do with a real double received from the client side on the server side.
This is something that needs to be solved.

It might be that this can be solved with `pattern`  property but then we should hide `setPattern`  API for such classes.

**Comment by dve** [comment]
Can't the pattern be useful to say: the integer must be tow digits long?

**Comment by denis-anisimov** [comment]
Yes, that's also true.
So it's not clear how how to handle situation when double is entered but server expects integer since it's a `IntegerNumberField`.

**Comment by dve** [comment]
From my point of view the behavoir is in sync with the behavior of the original `NumberField` - an exception is thrown from the parser

**Comment by nemojmenervirat** [comment]
It would be nice to have BigDecimal as value type.

**Comment by dve** [comment]
Yes, if we solved the problems I would create the other numeric types as well

**Comment by Legioth** [comment]
> It would be nice to have BigDecimal as value type.

This is not a trivial thing to do since the client-side implementation still treats the value as a 64-bit floating point number e.g. when adjusting the value to the configured precision.

Adding BigDecimal support on top of that would give a false sense of security. Updating the client-side implementation to use arbitrary precision arithmetics would instead require some additional investment and would also increase the download size of the web component.
