### ISSUE TITLE
setRequired should call setRequiredIndicator

### ISSUE THREAD

**Issue by tmattsso** [vaadin/vaadin-text-field-flow#16]
Currently the dev has to call both methods. It would be better if setRequired adds the indicator by default.

**Comment by ZheSun88** [comment]
for now, we don't need a separate step to set the `setRequiredIndicatorVisible` to `true`. But the indicator will not be shown, if the `label` property has not been set for the `TextField`. I am going to update the javadoc on the usage of the indicator.

**Comment by pleku** [comment]
This issue probably refers to `Binder` usage, when using https://github.com/vaadin/flow/blob/master/flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java#L601 the required indicator should be made visible. Did you verify that one @ZheSun88 ?

**Comment by pleku** [comment]
Binder uses `setRequiredIndicatorVisible()` https://github.com/vaadin/flow/blob/master/flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java#L801, if that is enough, then this issue can be closed.

**Comment by ZheSun88** [comment]
The problem with ticket is not related to the `setRequriedIndicatorVisible()`. Because the indicator has been set `::after` the `lable` property of the component itself. i have tested this with `beverage-starter` which is using binder for the field. so I think it is good enough to close this ticket now.
