### ISSUE TITLE
Inconsistent demo behaviors between java demo on Vcom and JS demos on CDN

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-text-field-flow#173]
with component version `1.3.0` (platform 13.0.4)

add a `NumberField` to UI, the type a decimal number `1.2`

you will see the behavior like on Vcom (this is the webcompoenent demo, but the java demo behaves also like this. )
![number-vcom](https://user-images.githubusercontent.com/31067185/56584500-85029a80-65e4-11e9-9018-adfc9cab02e9.gif)
the number will be rounded automatically. 

The user needs define `numberField.setStep(0.1)` for allowing decimals. 

furthermore, with the webcomponent(version 2.3.6, which is used in platform 13.0.4.) demo https://cdn.vaadin.com/vaadin-text-field/2.3.6/demo/#number-field-demos
the user can type decimal into the field freely, but not with the flow integration. 
![number-cdn](https://user-images.githubusercontent.com/31067185/56585038-b6c83100-65e5-11e9-8dc5-300b8262f416.gif)

**Comment by web-padawan** [comment]
Number field from 2.3.0 to 2.3.5 was behaving incorrectly. In fact, it was broken in many ways.
That has been fixed by vaadin/vaadin-text-field#343 and included to [2.3.6](https://github.com/vaadin/vaadin-text-field/releases/tag/v2.3.6) release.

This explains why it worked fine with CDN demos for that version, as mentioned above.

Vaadin 14 has a newer version and [demos](https://vaadin.com/components/vaadin-text-field/java-examples/number-field) don't have this issue anymore. Closing.
