### ISSUE TITLE
IntegerField - Component

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-text-field-flow#222]
- Create AbstractNumberFIeld with generic type
- Extend NumberField (Double, `<vaadin-number-field>`) and new IntegerField (Integer, `<vaadin-integer-field>`) from it

**Comment by pekam** [comment]
I'd like to verify one thing. Primitive type `double` can't be passed to a generic type parameter, so we need to use `Double` in `NumberField`. Currently its `value`-property uses `Double`, but `min/max/step` use the primitive `double`.

So my question is, is it a breaking change to change the method signatures:
```java
public void setMin(double min)
public double getMin()
```
to
```java
public void setMin(Double min)
public Double getMin()
```

In practice it doesn't seem to break anything, as `double` and `Double` can be used interchangeably, e.g.:
```java
double d = new Double(0.0);
d = 1.0 + new Double(1.0);
```
But still, it changes the signatures, so I'd like to be sure. @Legioth, do you have a quick answer to this?

**Comment by pekam** [comment]
Looks like it's a breaking change because of this case:
```java
setMin(1);
```
Passing an integer works when the argument type is `double`, but not after it's changed to `Double`.

So to avoid breaking changes, we need to either
1. Leave setters and getters for `min`, `max` and `step` out of the abstract super class, or
2. At least keep overloads with primitive `double` to `NumberField`

**Comment by Legioth** [comment]
Changing the getter return type causes problems if you have code like `int max = (int) field.getMax()`.

It seems like option 1. would be more appropriate.

**Comment by pekam** [comment]
Right. Thanks!
