### ISSUE TITLE
BigDecimalField

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-text-field-flow#224]
- Extend TextField (BigDecimal, `<vaadin-text-field>`)
- Add min/max (validate server-side)
- Use pattern and preventinvalidinput if possible to enfoce numeric input
See rest of the DoD in the Solution Proposal document.

**Comment by pekam** [comment]
Updated specs:
A Java field component, which:
- prevents user from typing invalid characters (not matching `^[\d-+.eE]$`) at client-side
- internally converts the string value to `BigDecimal` to have correct value type at server-side
    - invalid values, e.g. `e++2--` are converted to `null`, so it doesn't throw `NumberFormatException`
- provides numeric mobile keyboard on those browsers which support the `inputmode="numeric"` attribute
    - because the component can't use `<input type="number">`, this is the best we can do
- binds to `<vaadin-big-decimal-field>` component, which will be packaged with the Flow component
    - because it wouldn't bring any value to pure frontend users
    - technically, the client-side code could be just implemented on top of `vaadin-text-field`, but having the tag name matching the component class improves DX when binding it from a `PolymerTemplate` with `@Id`

Note:
- **no** up/down arrow key controls and -/+ buttons like with `NumberField` (because the browser can't calculate with big decimals)
- **no** `setMin`/`setMax` in the MVP
    - although it would align with `NumberField`
    - these component specific validation APIs don't integrate seamlessly with binder
    - because the web component won't have -/+ controls, setting min/max wouldn't provide a similar UX improvement as with `NumberField`

**Comment by pekam** [comment]
More things to consider:
- Localization of the decimal separator: as the input would have `type="text"`, this would need to be done by hand to have proper localization support
- As the main use case seems to be a money-field, would proper support of this use case require API for fixing the number of decimals?

**Comment by pekam** [comment]
@nemojmenervirat, you requested this feature in [another ticket](https://github.com/vaadin/vaadin-text-field-flow/issues/151#issuecomment-473641688).

Would you kindly help us with this component by providing your use case and all the things you would expect for this kind of a field?

**Comment by nemojmenervirat** [comment]
Hi, i will try to help :)

https://github.com/nemojmenervirat/test

In this project there is class

```
public class Invoice {
	private BigDecimal value;
	private BigDecimal tax;
        ...
}
```
If i want to bind it to some fields to allow user insert/update I tried two options, binding to `TextField `with converter, binding to `NumberField `with converter. At that time (when i posted feature request) i had problem with both options.

First when binding with `TextField `
```
binder.forField(textFieldValue).withConverter(new StringToBigDecimalConverter("Not a number")).bind(Invoice::getValue, Invoice::setValue);
```
I had problem because of NPE caused by `TextField.setValue(null)` on `Binder.setBean(invoice)` if `invoice.value = null`
I thought that problem is with `TextField.setValue` not allowing NULLS. I wrote something about that in https://github.com/vaadin/vaadin-text-field-flow/issues/78#issuecomment-473670653
Maybe it is, but custom converter can fix problem.

Second when binding with `NumberField` 
```
binder.forField(numberFieldTax).withConverter(new DoubleToBigDecimalConverter()).bind(Invoice::getTax, Invoice::setTax);
```
I had problem with not being able to display value with thousand separator (field Tax)

![image](https://user-images.githubusercontent.com/3105705/67143378-28b6c580-f26b-11e9-89d9-0819802e606d.png)

and when converting to `BigDecimal` I had to round values somewhere

![image](https://user-images.githubusercontent.com/3105705/67143365-0de45100-f26b-11e9-8d33-d0826a516034.png)

Right now I am using `TextField` with `CustomStringToBigDecimalConverter` something like in this test project, and it's good enough for me. Regarding `BigDecimalField` I have some ideas.

My suggestions:
 * option to auto add thousand separator while user is typing 
 * option to set format for example `new DecimalFormat("###,###,##0.00")` and if I use `BigDecimalField.setValue(BigDecimal.ONE)` I would see 
![image](https://user-images.githubusercontent.com/3105705/67143597-4b49de00-f26d-11e9-857b-f9506091d25c.png)
 * option to enable insert mode, same effect as when you press Insert key in command prompt and when you type you overwrite (this option can be useful on text field)
 * maybe up and down keys can be used while insert mode is active to increase or decrease value of current digit

**Comment by pekam** [comment]
Thanks a lot for the detailed description @nemojmenervirat!

We have already created a basic implementation of `BigDecimalField` in #244. It has only really basic conversion between `String` and `BigDecimal`, and it prevents typing anything else than numbers, `-`, `+` and `.`.

Based on your description, it unfortunately sounds like our new component isn't optimal for your use case. You probably want to keep your current implementation if you prefer to have comma as the thousand separator.

To include `BigDecimalField` in Vaadin 14.1, we are not able to include additional features at this point.

We might add API for better control of the formatting later if it seems like a highly requested feature. Let's see what kind of feedback we get from others after releasing the first component version.

> option to auto add thousand separator while user is typing

Btw, have you seen [this add-on](https://vaadin.com/directory/component/textfield-formatter)? It might work for this feature.

**Comment by nemojmenervirat** [comment]
I didn't see that add-on. It looks great, and I will definitely try it. Thank you for information.

**Comment by szaniszlaid** [comment]
> requested feature

What is the platform to "request this feature"? I'd like to add custom validation while the field converts String to BigDecimal.
Thanks

**Comment by pekam** [comment]
@szaniszlaid, you can [create a new issue to this repository](https://github.com/vaadin/vaadin-text-field-flow/issues/new) describing the feature request.
