### ISSUE TITLE
NumberField value expressed in scientific notation

### ISSUE THREAD

**Issue by allenvpn312** [vaadin/vaadin-text-field-flow#243]
Currently NumberField value is expressed in scientific notation when the value exceeds 9,999,999.  NumberField should support values 10,000,00 and greater to support accounting and financial applications.  I've tested this by changing the value to 9,999,999 and it displays fine but when the value hits 10,000,000 or greater, the value is shown in scientific notation.

![image](https://user-images.githubusercontent.com/9533785/66982490-d3689180-f07b-11e9-843b-393231150dff.png)

**Comment by allenvpn312** [comment]
I am able to reproduce this, if I change the value to 9,999,999 the field displays the value fine.  Is there a limit set for the max value?

![image](https://user-images.githubusercontent.com/9533785/67034022-8a94f500-f0dc-11e9-8d54-1c67b857dd99.png)

**Comment by pekam** [comment]
Hi!

This seems to be fixed by a recent PR #232. It will be included in `vaadin-text-field-flow` 2.0.6, and most likely in the next maintenance release Vaadin 14.0.10.

Previously the component used simply `Double::toString` to format the value from server to client representation, which is implemented so that it uses the `E`-notation for big round values.
