### ISSUE TITLE
BigDecimalField does not use locale

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin/vaadin-text-field-flow#258]
Displaying a floating-point value in `BigDecimalField` does not seem to take locale into consideration.

It is inconsistent with `NumberField`, which apparently converts the value with proper locale.

![screen shot](https://user-images.githubusercontent.com/1917965/67850783-c0d96800-fb11-11e9-994c-e60913c15a6a.png)

**Comment by Legioth** [comment]
Comparing with `NumberField` is actually slightly unfortunate since it handles locales based on the browser's settings rather than using any local setting from the server. `BigDecimalField` should instead format its values based on the same server-side locale settings that are used by other parts of the framework (i.e. based on `UI.getLocale`).

When it comes to `BigDecimalField`, the recommended way of handling locale-sensitive parsing and formatting is described in https://stackoverflow.com/questions/12836647/best-way-to-convert-locale-specific-string-to-bigdecimal.

**Comment by pekam** [comment]
Here's one possible implementation with `UI::getLocale`: https://github.com/vaadin/vaadin-text-field-flow/compare/big-decimal-field-decimal-separator
Maybe the `NumberFormat`/`DecimalFormat` approach would be cleaner than replacing characters manually. But the separator character needs to be retrieved anyway, to update which characters should be prevented at client-side.

I don't think thousand separators should be supported. It could cause users to make huge errors in the values they send, if they are not sure which separator is used for decimals and which one for thousands.

**Comment by pekam** [comment]
I found out that there's a `LocaleChangeObserver` interface, which should automatically notify the implementing component when the locale changes. This could be good addition to my implementation, to update the client-side separator. The downside is that it would add public API `localeChange` which shouldn't really be public to `BigDecimalField` users.

**Comment by Legioth** [comment]
Shouldn't it be up to the application developer to choose whether a thousands separator is used? There are also other thousands separators than `.` that won't cause as much risk for ambiguity, e.g. ` `.

**Comment by tomivirkki** [comment]
Also note that thousands separator might not be the same as millions separator. German format is "4 294 967.295,000" according to https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html
Suggestion: accept the [currently open PR](https://github.com/vaadin/vaadin-text-field-flow/pull/262) as the default (only radix is supported, detection based on UI locale) and in a later minor expose methods for custom formatting and parsing of the value (ideally for both number type fields). Doing this for NumberField adds some complexity as the formatting needs to happen client-side (due to value up/down buttons feature)

**Comment by pekam** [comment]
Based on our f2f discussion, I've updated my PR #262 to include setter and getter methods for the Locale.
