### ISSUE TITLE
De-bounce/throttle value change events

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-text-field-flow#33]
At the moment value change events are sent to the server real-time while the user is typing on the field, resulting in a large amount of requests (and server-side callback executions) that might be unnecessary until the user stops typing.

A method to configure a timeout for throttle/de-bouncing the value change events would help to reduce/avoid this.

**Comment by Legioth** [comment]
Related to this overall Flow issue: https://github.com/vaadin/flow/issues/467

**Comment by mstahv** [comment]
And the requests are not small. This is a serious issue that will cause many evaluators to drop the product.

Consider a text area with 100kb of text, user types in an other sentence, say 100 characters. This causes 10 megabytes to be sent to the server, which is unacceptable.

With older Vaadin, 100kb was sent to the server, which is fine.

**Comment by pleku** [comment]
I don't think this is an issue anymore since
- the default event used for input fields value change is not fired for each keypress
- there are ways for debouncing the events for any DOM event type

What is still remaining, is to make it happen easily for certain component level events easily, eg. https://github.com/vaadin/flow/issues/4016 & https://github.com/vaadin/flow/issues/4017

**Comment by heruan** [comment]
Great to hear this is possible now! Do you have any example on how to set a debounce for a `TextField`?

**Comment by mstahv** [comment]
AFAIK it is not (easily) possible yet. Waiting for #4017, that I assume to somehow fix this as well.
