### ISSUE TITLE
Nonsense initial value change event

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-text-field-flow#41]
```
TextField textField = new TextField();
System.out.println("TextField default is " + textField.getValue());
textField.addValueChangeListener(e -> {
	System.out.println("TextField value changed from " + e.getOldValue() + " to "
		+ e.getValue());
});
```

Expected output:
```
TextField default is
```

Actual output:
```
TextField default is
TextField value changed from null to
```

**Comment by Artur-** [comment]
Happens also for `TextArea`

**Comment by denis-anisimov** [comment]
The reason of this behavior is the following:
- Client side `vaadin-text-field` element defines `value` property with the default value `''`.
- Server side `value` has no value set and it's not sent to the client as a result.
- It means that Flow sends the client side default value to the server to sync their values.
- As a result the listener is invoked because the value has been set from the client side.

The simplest possible fix to call `setValue("")` for the text field (in its CTOR e.g.) doesn't work since we have a concept of `emptyValue` which is `""`  and replaces by itself the `null` which is the default value of the component.

I'm not sure at the moment how this should be fixed.
