### ISSUE TITLE
make the `addToPrefix()` method public

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-text-field-flow#47]
As a developer I would like to use the [addToPrefix](https://github.com/vaadin/vaadin-text-field-flow/blob/master/src/main/java/com/vaadin/flow/component/textfield/GeneratedVaadinTextField.java#L936) method. Please make it public.

**Comment by pleku** [comment]
Why? Please explain the use case.

**Comment by vlukashov** [comment]
The TextFIeld component might be used in different contexts. Bakery uses it also to input a price:
```java
@Id("price")
private TextFieldWithPrefix priceField;
...
priceField.addToPrefix(new Span("$"));
```

**Comment by pleku** [comment]
I wonder if it would make sense for allowing this only for e.g. `Span`. Mayhaps would be nice also to be able to easily add any icon there, which then again might mean that we have to support `Component`.

**Comment by pekam** [comment]
This is also used in Beverage Buddy to add an icon to the search field:
`searchField.addToPrefix(new Icon("lumo", "magnifier"));`

**Comment by manolo** [comment]
IMO making all the API of a WC protected is not a good idea, is responsability of the WC author to define what is the public API of their elements, and responsability of flow generator to mark as protected only those cases that they cannot handle like setting functions.
In my opinion each time, there is a lot of boiler-plate code that the flow developer needs to use a web component from server side, and having to develop a wc-flow overriding all single method in the generated class is not a good DX.

**Comment by pekam** [comment]
I think the Java API actually needs a bit more design:
 - Currently the method takes any number of components, but I can't think of an use-case for adding more than one component there, and it also looks ugly because the components are stacked on top of each other and can't fit into the text-field.
 -> take only one component as a parameter
 - There's no way of retrieving or removing the added component. You can't for example change the icon after adding it. One use-case would be doing server-side validation for the field and changing the icon from X to checked when the input is valid.
 -> getters and setters instead of "add"

So I would propose the following API:
```java
public void setPrefixComponent(Component prefixComponent)
public Component getPrefixComponent()

public void setSuffixComponent(Component suffixComponent)
public Component getSuffixComponent()
```
Please comment if you come up with a better naming convention.

**Comment by pekam** [comment]
The PR is merged with the above API changes, so after the next release you can use `setPrefixComponent()`
