### ISSUE TITLE
Do not clear error message when the field becomes valid

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-text-field-flow#9]
When the field becomes valid, the error message is cleared and removed from the DOM. This can cause issues with themes that expect the error message to remain in the DOM, for the purpose of transitions/animations.

The `vaadin-text-field` element hides the error message automatically when the field is valid, so there shouldn’t be a need to remove the text content of the message:
https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-text-field.html#L130

Here’s the unwanted behavior - the error message vanishes too quickly:
![error-message-removed](https://user-images.githubusercontent.com/66382/31930687-4774081e-b8a9-11e7-8fc2-89d13c8dbf1c.gif)

Here’s the desired behavior – the error message is nicely curtained/collapsed:
![error-message-not-removed](https://user-images.githubusercontent.com/66382/31930716-6353b76e-b8a9-11e7-9395-7f7a7e2e85df.gif)

This could also be a Vaadin Flow Binder issue, so feel free to move it to a more appropriate repo if needed.

**Comment by denis-anisimov** [comment]
That's the Flow binder issue definitely.
There is a code that clears the error message when the field should become valid.

The problem here is that it's the common behavior: binder doesn't distinguish text field or any other component.
It executes the logic for any `HasValidation` component.
As a result there is the question: is it true that it's enough to update only the status without the error message for any component which allows to set error message and "valid/invalid" status ?

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/flow #3439](https://github.com/vaadin/flow/issues/3439) via [**ZenHub**](https://www.zenhub.com/)
